### ISSUE TITLE
Passing credentials via env vars

### ISSUE THREAD

**Issue by ItalyPaleAle** [jaemk/migrant#15]
Is there a way to pass credentials (database name, username, password) using environmental variables? This way, they can be stored outside of source control and managed as secrets.

**Comment by jaemk** [comment]
env variables are currently supported by defining values in your `Migrant.toml` file with the format `env:ENV_VAR_NAME`. I'm realizing I may have added this for myself and never added it to documentation (for the `migrant` cli tool and for `migrant_lib`). Here's an example of how to use env vars https://github.com/jaemk/transfer/blob/dcd39189076cd537f52184c6707e1455148c2f41/Migrant.toml#L6

**Comment by ItalyPaleAle** [comment]
That's precisely what I was looking for. Thanks for the quick response!
